<?= $this->doctype(); ?>
<!--
           _ _ _             
  __ _  __| (_) |_ _   _ ___ 
 / _` |/ _` | | __| | | / __|
| (_| | (_| | | |_| |_| \__ \
 \__,_|\__,_|_|\__|\__,_|___/ v2.0

-->
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html> <![endif]-->
<!--[if !IE]><!--><html><!-- <![endif]-->
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Aditus')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0')
            ->appendName('apple-mobile-web-app-capable', 'yes')
            ->appendName('apple-mobile-web-app-status-bar-style', 'black')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=9; IE=8; IE=7; IE=EDGE')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet('/css/tablesaw.css')
            ->appendStylesheet('/css/styles.css')
            ->appendStylesheet('//cloud.typography.com/6761252/788422/css/fonts.css')
        ?>

        <!-- <link rel="stylesheet/less" href="<?= sprintf('/assets/less/admin/global.less?v=%s', time()); ?>" /> -->

    </head>
    <body class="blog sidebar-mini">
        
        <?= $this->render('layout/header.phtml'); ?>

        <div id="content">
            <div id="content-wrapper" class="innerLR">
                <?= $content; ?>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="innerTB">&nbsp;</div>
        
        <?= $this->render('layout/footer.phtml'); ?>

        <!-- Global -->
        <script>
            var basePath = '',
                commonPath = '/assets/',
                rootPath = '/',
                DEV = false,
                jqueryPath = '/js/lib/jquery/dist/jquery.min.js',
                highchartsPath = '/js/lib/highcharts/highcharts.js',
                componentsPath = '/assets/components/';

        </script>

        <script src='/js/lib/jquery/dist/jquery.min.js'></script>
        <script src='/js/lib/highcharts/highcharts.js'></script>
        <script src='/js/lib/highcharts/highcharts-more.js'></script>
        <script src='/js/lib/highcharts/modules/exporting.js'></script>
        <script src='/js/lib/canvg.js'></script>
        <script src='/js/lib/rgbcolor.js'></script>        

        <script src="/assets/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v1.2.3"></script>
        <script src="/assets/components/library/modernizr/modernizr.js"></script>
        <script src="/assets/components/core/js/sidebar.main.init.js?v=v1.2.3"></script>
        <script src="/assets/components/core/js/sidebar.collapse.init.js?v=v1.2.3"></script>

        <script src="/assets/components/modules/admin/tables/datatables/assets/lib/js/jquery.dataTables.min.js"></script>
        <script src="/assets/components/modules/admin/tables/datatables/assets/lib/extras/TableTools/media/js/TableTools.min.js"></script>
        <script src="/assets/components/modules/admin/tables/datatables/assets/lib/extras/ColVis/media/js/ColVis.min.js"></script>
        <script src="/assets/components/modules/admin/tables/datatables/assets/custom/js/DT_bootstrap.js"></script>
        <script src="/assets/components/modules/admin/tables/datatables/assets/custom/js/datatables.init.js"></script>

        <script src="/assets/components/modules/admin/tables/classic/assets/js/tables-classic.init.js"></script>
        <script src="/assets/components/plugins/holder/holder.js"></script>

        <script data-main="/js/main" src="/js/lib/requirejs/require.js"></script>

        <!-- <script src="js/require_main.built.js"></script> -->

        <?php // echo $this->partial('primus/elements/modal', array('id'=>'modal')); ?>

        <script type="text/javascript">            
            Highcharts.setOptions({
                exporting: {
                    enabled: false
                }
            });

            function getSVG( chart ){
                svg = chart.getSVG();
                svg = svg.replace('rx="5"', 'rx="0"');
                svg = svg.replace('ry="5"', 'ry="0"');
                return svg;
            }

            $(function() {

                $('.printBtn').click(function(){
                    var form = $(this).parents('form:first');
                    $('#processingModal').on('show.bs.modal', function(){

                        for(var chartCnt = 0; chartCnt < Highcharts.charts.length; chartCnt++)
                        {
                            var chart = Highcharts.charts[chartCnt];            
                            if( chart !== undefined ){
                                var chartId = chart.renderTo.id;
                                var canvasId = 'chart_' + chartId + '_canvas';
                                svg = getSVG( chart );

                                var canvas = $('<canvas />').attr({
                                    id: canvasId
                                });        
                                $('#hiddenCanvas').append( canvas );

                                canvg(document.getElementById(canvasId), svg);
                                canvas = document.getElementById(canvasId);
                                dataUrl = canvas.toDataURL();
                                console.log(dataUrl);

                                $('<input>').attr({
                                    type: 'hidden',
                                    name: 'svg['+chartId+']',
                                    value: dataUrl
                                }).appendTo($(form));
                            }
                        }                        
                                            
                        $(form).submit();
                    }).modal('show');
                });

            });     

        </script>

        <?= $this->inlineScript(); ?>

        <div id="hiddenCanvas"></div>

        <?php /* echo $this->partial('primus/elements/modal', array('id'=>'processingModal', 'body'=>'
            <div class="text-center">
                <i class="fa fa-spinner fa-spin" style="font-size: 38px;"></i>
                <p style="font-size: 20px; padding-top: 20px;">Processing</p>
            </div>
        ')); */ ?>
    </body>
</html>