<?= $this->doctype(); ?>

<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html> <![endif]-->
<!--[if !IE]><!--><html><!-- <![endif]-->
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Aditus')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0')
            ->appendName('apple-mobile-web-app-capable', 'yes')
            ->appendName('apple-mobile-web-app-status-bar-style', 'black')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=9; IE=8; IE=7; IE=EDGE')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet('/css/tablesaw.css')
            ->appendStylesheet('/css/styles.css')
            ->appendStylesheet('/css/cover.css')
            ->appendStylesheet('//cloud.typography.com/6761252/788422/css/fonts.css')
        ?>

        <!-- <link rel="stylesheet/less" href="<?= sprintf('/assets/less/admin/global.less?v=%s', time()); ?>" /> -->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body class="loginWrapper">

        <div class="site-wrapper">

            <div class="site-wrapper-inner">

                <div class="cover-container">

                    <div class="inner cover">
                        <?= $content; ?>
                    </div>

                </div>

            </div>

        </div>


        <!-- Global -->
        <script>
            var basePath = '',
                commonPath = '/assets/',
                rootPath = '/',
                DEV = false,
                componentsPath = '/assets/components/';
        </script>

        <script data-main="/js/main" src="/js/lib/requirejs/require.js"></script>
        <!-- <script src="js/require_main.built.js"></script> -->

        <?= $this->inlineScript(); ?>
    </body>
</html>