<div class="innerLR">
    <div class="row innerTB">
        <div class="col-sm-2 text-center">
            <img class="" src="/img/icons/feedback.png" width="60" />
        </div>
        <div class="col-sm-10">
            <h3 class="no-transform medium-weight modal-title">Add Feedback</h3>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="row innerTB">
        <div class="col-sm-12 text-center">
            <i class="fa fa-check-circle" style="color: #74BD79; font-size: 80px;"></i>
            <div class="light-text" style="padding-top: 20px">Feedback Submitted!</div>
            <p>Thank you for providing feedback.</p>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="row innerTB">
        <div class="col-sm-12 text-center">
            <button type="button" class="btn btn-inverse btn-stroke" data-dismiss="modal">Close</button>
        </div>
    </div>                    
</div>
