	<div class="innerLR">
	    <div class="row innerTB">
	        <div class="col-sm-2 text-center">
	            <img class="" src="/img/icons/add-fund.png" width="60" />
	        </div>
	        <div class="col-sm-10">
	            <h3 class="no-transform medium-weight modal-title">Delete Fund</h3>
	        </div>
	    </div>

	    <div class="clearfix"></div>

	    <div class="row innerTB">
	        <div class="col-sm-12 text-center">
	            <i class="fa fa-check-circle" style="color: #74BD79; font-size: 80px;"></i>
	            <div class="light-text" style="padding-top: 20px">Fund Deleted Successfully!</div>
	        </div>
	    </div>

	    <div class="clearfix"></div>

	    <div class="row innerAll">
	        <div class="col-sm-12">
	            <div class="row">
	            	<div class="col-sm-4 col-sm-offset-4 text-center">
	            		<a href="<?= $this->url('portfolio'); ?>" class="btn btn-inverse btn-stroke">Continue</a>
	            	</div>
	            </div>
	        </div>
	    </div>
	</div>