<?php $loginForm->prepare(); ?>

<div class="login spacing-x2 text-center">
    <div><img class="" src="/img/icons/user.png" /></div>
    <div class="heading">Welcome to Aditus</div>

    <div class="message">
        If you've already registered, please enter your email address and password below, then click the Sign In button.
    </div>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <?= $this->form()->openTag($loginForm->setAttribute('action', $this->url('login'))); ?>
                <div class="form-group">
                    <?= $this->formElement($loginForm->get('email')->setAttribute('class','form-control text-center')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($loginForm->get('secret')->setAttribute('class','form-control text-center')); ?>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="forgot">FORGOT PASSWORD</div>
                        </div>
                        <div class="col-sm-4 text-center">
                            <i class="fa fa-lock"></i>
                        </div>
                        <div class="col-sm-4">
                            <button type="submit" class="form-control btn btn-inverse btn-stroke">Sign In</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>