<div class="login spacing-x2" style="margin-top: 80px;">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
            <div><img class="" src="/img/icons/user.png" /></div>
            <div class="heading">Welcome to Aditus<sup>BETA</sup></div>

            <div class="message">
                Please register below to access Aditus and participate in our beta program.
            </div>

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 text-center">
                    <i class="fa fa-check-circle" style="font-size: 80px;"></i>
                    <div class="message" style="padding-top: 20px">Registration Complete!</div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">                        
                        <a href="<?= $this->url('portfolio'); ?>" class="btn btn-inverse btn-stroke medium-weight" style="padding-left:30px; padding-right:30px;">Continue</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>